package Assessment;
import javax.persistence.*;
import java.util.*;

public class MainClass {
	
	public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("postgres") ; 
		EntityManager em = emf.createEntityManager() ; 
		EntityTransaction et = em.getTransaction() ;
//		CustomerService cs = new CustomerService();
//		Customer c = new Customer() ; 
//		c.setEmail("abcde@gmail.com");
//		c.setName("Ser");
//		c.setPhone("9876543210");
//		Address a = new Address() ; 
//		a.setC(c);
//		a.setCity("Patna");
//		a.setPincode("4568");
//		a.setState("Bihar");
//		c.setA(a);
		Lead l = new Lead() ; 
		l.setSource("Soruce");
		l.setStatus("Delivered");
//		l.setC(c);
//		c.setL(l);
//		et.begin();
//		em.persist(l);
//		em.persist(a);
//		et.commit();
//		cs.register(c);
//		cs.update(2,"bcd@gmail.com");
		LeadService ls = new LeadService() ;
//		Lead l = new Lead() ;
//		l.setSource("Soruces");
//		l.setStatus("Pending");
//		Customer c = em.find(Customer.class, 3) ; 
//		l.setC(c);
//		ls.register(l);
//		SalesEmployee s1 = new SalesEmployee() ; 
//		s1.setDepartment("Depr");
//		s1.setName("Hello");
//		Lead l = em.find(Lead.class, 1002) ; 
//		s1.setL(l); 
//		SalesEmployee s2 = new SalesEmployee() ; 
//		s2.setDepartment("Dept");
//		s2.setName("Roushan");
//		s2.setL(l);
//		List<SalesEmployee> list = new ArrayList<>() ; 
//		et.begin();
//		em.persist(s1);
//		em.persist(s2);
//		et.commit();
//		ls.update(1001, list);
//		Order o = new Order() ; 
//		o.setAmount(1600.0);
//		o.setDate("18-12-2026");
//		o.setL(l);
//		OrderService os = new OrderService() ; 
//		os.register(o);
//		Product p = new Product() ;
//		p.setAmount(2000.0);
//		p.setName("Patanjali ghee");
		List<Order> ol = new ArrayList<>() ;
//		List<SalesEmployee> se = new ArrayList<>() ;
		Order o1 = em.find(Order.class, 10004) ; 
		Order o2 = em.find(Order.class , 10005) ; 
		ol.add(o2) ; 
		ol.add(o1) ;
//		SalesEmployee s1 = em.find(SalesEmployee.class , 11000) ; 
//		SalesEmployee s2 = em.find(SalesEmployee.class , 11001) ;
//		se.add(s1) ; 
//		se.add(s2) ; 
//		p.setOl(ol);
//		p.setSe(se);
//		ProductService ps = new ProductService() ; 
//		ps.register(p);
//		SupportTicket st = new SupportTicket() ; 
//		st.setIssue("Very big issue");
//		st.setStatus("Solved");
//		st.setO(o2);
//		TicketService ts = new TicketService() ; 
//		ts.register(st);
//		CustomerService cs1 = new CustomerService() ;
//		cs1.delete(3); // delete executed 
		OrderService os = new OrderService()  ; 
		os.totalCalculation();
	}
}
